name: Flutter App Distribution

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'use java11'
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.2'  # Remplacez par votre version de Flutter

      # - name: Install Fastlane for ios
      #   working-directory: ./ios
      #   run: gem install bundler && bundle install

      # - name: Build and deploy to Firebase App Distribution for IOS
      #   env:
      #     FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      #   working-directory: ./ios
      #   run: |
      #     fastlane custom_lane

      - name: Install Fastlane for android
        working-directory: ./android
        run: gem install bundler && bundle install

      - name: Build and deploy to Firebase App Distribution for Android
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        working-directory: ./android
        run: |
          fastlane deploy_to_firebase